### ISSUE TITLE
small d method overwritten

### ISSUE THREAD

**Issue by ryanlevy** [moble/spherical#17]
in the `Wigner.__init__` function, `self.d` overwrites the method `d(self, expiβ, out=None, workspace=None)` which in turn causes `spherical.wigner_d(...)` to fail

**Comment by moble** [comment]
Thanks for the report.  And sorry about it.  I guess I pretty much never use `d`, and mostly moved over to using [the Julia version](https://github.com/moble/SphericalFunctions.jl) shortly after reworking the code, so I just never ran into this problem.

Currently, I'm still struggling with the demon beast that is python packaging, but hopefully this will be fixed shortly by #18.

**Comment by ryanlevy** [comment]
Thanks for the quick fix!
